project:
  type: website
  output-dir: docs

website:
  title: "Bezia Lemma"
  search: false
  sidebar:
    search: false
    contents:
      - section: "Protocols"
        contents:
          - "protocols/cryoslicing.qmd"
          - "protocols/immunostaining.qmd"
          - "protocols/lung_culture.qmd"
      - section: "Tutorials"
        contents:
          - "tutorials/install_julia.qmd"
          - "tutorials/microscopy_training_checklist.qmd"
          - "tutorials/two_photon_microscopy.qmd"
      - section: "Stories"
        contents:
          - "stories/annapurnacrescent.qmd"
          - "stories/coexistence.qmd"
          - "stories/first.qmd"
          - "stories/mareksdisease.qmd"
      - section: "Other"
        contents:
          - "other/active_nematic_tennis.qmd"
          - "other/sphere_of_life.qmd"
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

engines: ['julia']


