project:
  type: website
  output-dir: docs

website:
  title: "Bezia Lemma"
  sidebar:
    contents:
      - section: "Protocols"
        contents:
          - "protocols/cryoslicing.qmd"
          - "protocols/immunostaining.qmd"
      - section: "Tutorials"
        contents:
          - "tutorials/install_julia.qmd"
          - "tutorials/microscopy_training_checklist.qmd"
          - "tutorials/two_photon_microscopy.qmd"
      - section: "Stories"
        contents:
          - "stories/annapurnacrescent.qmd"
          - "stories/coexistence.qmd"
    search: false
format:
  html:
    theme:
      - cosmo
    css: styles.css
    toc: true

engines: ['julia']


