---
title: "First!"
format:
  html:
    css: [../stories/storyspecific.scss"]
---
 
The premise of FutureCore was simple: we were going to discover everything first. We would discover every cancer treatment, every law of physics, every sociological phenomenon before anyone else. 

We got the idea from Jessie. Jessie had worked in a condensed matter physics lab, where he studied the impact of line defects in graphene on conductivity band gaps. After presenting his findings at a conference, another scientist published a theory paper on Jessie's experiments the next day, leading his professor to dismiss his continued research as redundant.

This incident left Jessie questioning the academic emphasis on being first, which seemed to undervalue any subsequent research. It reminded us of early online message boards where only the earliest comments mattered. Often the first comment would just say "First!". Like in an online message board, the essential part of science was to be the first one to a discovery.

We wanted to name our company First! , but it was trademarked, so we went with FutureCore. Issac built a generative AI to write papers, and we fed it preprint papers and speech-to-text transcripts from conference recordings. We posted 14,000 papers that first year. We contacted former classmates and alumni listservs to get real people's credentials with university emails. 

We had some promising early work, a few paper synthesizing two fields together to form major scientific breakthroughs. But our generative AI was at its best as a tool for remixing existing language and we were hungry for unpublished text. So we moved to the mecca of research, Boston, where we recorded every talk we could go to. To open a few doors, literally, I started taking HarvardX courses, and Jessie got into a PhD program at BU.

Issac pushed the gAI technology. He created a double-layered AI, in which the first AI would make a discovery, and then the second AI would grade each statements likeliness. We could then publish a distribution of unlikely to likely discoveries. This double-layered AI was the heart of the FutureCore discovery engine, and is one of the few things we never published about.

We made some huge discoveries, and we made them first. We discovered that a portion of the dynein complex docking inside the hollow space of a microtubule changed the dispersion relation for lattice phonons. We discovered a meaning for entropic time in negative temperatures that was the basis for macrowave machines people use to cool their tea today. We discovered a geometry for nuclear fusion, a spherical stellarator configuration, which Livermore Labs clarified and built two years later. I had the pleasure of being an author on the now infamous paper discovering the idea of spontaneous phase generation in granular materials.

We built a preprint server to help us aggregate new ideas and get more analytics on which of our papers were being skimmed or ignored. The broad-scope preprint server Pre-Prints for Engineering, News, Investigations, and Science. We could pull ignored papers and highlight where people stopped skimming and closed the paper. It was a terrific resource, but it was costly to run. 

As we scaled and secured funding, we hired skilled computer scientists to help build up our generational AI and began filing patents. We even started to float the idea of doing some in-house experiments to solidify some of our famous papers. We started a competition for undergraduate and graduate students at universities nationwide. We offered a cash prize for the best idea, judged by technical accuracy, feasibility, and scientific impact. We never gave out any awards, but thousands of students sent in submissions that went to our AI. 
In our heyday, 5 million research papers were put online in some form every year. We couldn't even scale to a million papers a year, so we couldn't capture more than 20% of scientific discoveries. In hindsight, we handicapped our speed of discovery. We had each paper focus on just one scientific discovery, and we spent too much time generating internal documents for future patents. 

Then ThinkBlue came in, powered by the richest man on the planet, with an army of researchers. They jammed several discoveries into each paper and didn't generate tertiary documents. Instead of patents, ThinkBlue bought the companies necessary to turn its discoveries into realities. They pioneered the now common "mentoring and administrative lead" strategy to shift the credit of successful discoveries to a set of permanent employees while piling misleading discoveries onto ghost researchers.

On FutureCore's fourth birthday, we sold it to an AI software giant looking to enter the generative discovery space. We hired more lawyers to negotiate the sale than we had ever hired actual employees to fuel our discoveries. By the end of the decade, to a rounding error, ThinkBlue discovered everything first, not us. The rate of scientific advancement has plummeted, there isn’t much left to discover. Scientists are no longer the first to make discoveries, and thus funders feel their work is irrelevant. Many scientists have moved on to more important pursuits such as finance and ice fishing.

I'm spending my winnings funding my anti-aging biotech institution: FollowUP. I hire scientists to validate the discoveries that marked my tenure at FutureCore. No publishing or grant applications. Researchers propose their needs and if justified, I provide the necessary resources. Rather than racing to be first, my scientists can focus on validating whether or not something we already know is true.

